// STATE NAME DATA
export const DISPATCH_DETAILS_REQUEST = 'DISPATCH_DETAILS_REQUEST'
export const DISPATCH_DETAILS_SUCCESS = 'DISPATCH_DETAILS_SUCCESS'
export const DISPATCH_DETAILS_FAIL = 'DISPATCH_DETAILS_FAIL'


export const GET_DISPATCH_DETAILS_DATA_REQUEST = 'GET_DISPATCH_DETAILS_DATA_REQUEST'
export const GET_DISPATCH_DETAILS_DATA_SUCCESS = 'GET_DISPATCH_DETAILS_DATA_SUCCESS'
export const GET_DISPATCH_DETAILS_DATA_FAIL = 'GET_DISPATCH_DETAILS_DATA_FAIL'

export const GET_DISPATCH_DETAILS_DATA_BYID_REQUEST = 'GET_DISPATCH_DETAILS_DATA_BYID_REQUEST'
export const GET_DISPATCH_DETAILS_DATA_BYID_SUCCESS = 'GET_DISPATCH_DETAILS_DATA_BYID_SUCCESS'
export const GET_DISPATCH_DETAILS_DATA_BYID_FAIL = 'GET_DISPATCH_DETAILS_DATA_BYID_FAIL'


export const PRODUCTION_DETAILS_REQUEST = 'PRODUCTION_DETAILS_REQUEST'
export const PRODUCTION_DETAILS_SUCCESS = 'PRODUCTION_DETAILS_SUCCESS'
export const PRODUCTION_DETAILS_FAIL = 'PRODUCTION_DETAILS_FAIL'

export const GET_PRODUCTION_DETAILS_DATA_REQUEST = 'GET_PRODUCTION_DETAILS_DATA_REQUEST'
export const GET_PRODUCTION_DETAILS_DATA_SUCCESS = 'GET_PRODUCTION_DETAILS_DATA_SUCCESS'
export const GET_PRODUCTION_DETAILS_DATA_FAIL = 'GET_PRODUCTION_DETAILS_DATA_FAIL'


// GET_PRODUCTION_DETAILS_DATA_BY_ID_REQUEST
export const GET_PRODUCTION_DETAILS_DATA_BY_ID_REQUEST = 'GET_PRODUCTION_DETAILS_DATA_BY_ID_REQUEST'
export const GET_PRODUCTION_DETAILS_DATA_BY_ID_SUCCESS = 'GET_PRODUCTION_DETAILS_DATA_BY_ID_SUCCESS'
export const GET_PRODUCTION_DETAILS_DATA_BY_ID_FAIL = 'GET_PRODUCTION_DETAILS_DATA_BY_ID_FAIL'

// GET_PRODUCTION_DETAILS_DATA_BY_ID_REQUEST
export const GET_DHR_UPLOAD_FILE_REQUEST = 'GET_DHR_UPLOAD_FILE_REQUEST'
export const GET_DHR_UPLOAD_FILE_SUCCESS = 'GET_DHR_UPLOAD_FILE_SUCCESS'
export const GET_DHR_UPLOAD_FILE_FAIL = 'GET_DHR_UPLOAD_FILE_FAIL'

// GET_PINCODE_DATA_REQUEST
export const GET_PINCODE_DATA_REQUEST = 'GET_PINCODE_DATA_REQUEST'
export const GET_PINCODE_DATA_SUCCESS = 'GET_PINCODE_DATA_SUCCESS'
export const GET_PINCODE_DATA_FAIL = 'GET_PINCODE_DATA_FAIL'

// GET_DEVICEID_FROM_PRODUCTION_REQUEST
export const GET_DEVICEID_FROM_PRODUCTION_REQUEST = 'GET_DEVICEID_FROM_PRODUCTION_REQUEST'
export const GET_DEVICEID_FROM_PRODUCTION_SUCCESS = 'GET_DEVICEID_FROM_PRODUCTION_SUCCESS'
export const GET_DEVICEID_FROM_PRODUCTION_FAIL = 'GET_DEVICEID_FROM_PRODUCTION_FAIL'

// GET_EDIT_DISPATCH_DATA_REQUEST
export const GET_EDIT_DISPATCH_DATA_REQUEST = 'GET_EDIT_DISPATCH_DATA_REQUEST'
export const GET_EDIT_DISPATCH_DATA_SUCCESS = 'GET_EDIT_DISPATCH_DATA_SUCCESS'
export const GET_EDIT_DISPATCH_DATA_FAIL = 'GET_EDIT_DISPATCH_DATA_FAIL'



// GET_SINGLE_HOSPITAL_DETAILS_REQUEST
export const GET_SINGLE_HOSPITAL_DETAILS_REQUEST = 'GET_SINGLE_HOSPITAL_DETAILS_REQUEST'
export const GET_SINGLE_HOSPITAL_DETAILS_SUCCESS = 'GET_SINGLE_HOSPITAL_DETAILS_SUCCESS'
export const GET_SINGLE_HOSPITAL_DETAILS_FAIL = 'GET_SINGLE_HOSPITAL_DETAILS_FAIL'



// GET_SERIAL_NUMBER_LIST_REQUEST
export const GET_SERIAL_NUMBER_LIST_REQUEST = 'GET_SERIAL_NUMBER_LIST_REQUEST'
export const GET_SERIAL_NUMBER_LIST_SUCCESS = 'GET_SERIAL_NUMBER_LIST_SUCCESS'
export const GET_SERIAL_NUMBER_LIST_FAIL = 'GET_SERIAL_NUMBER_LIST_FAIL'



// GET_SINGLE_SERIAL_NO_TRACK_DATA_REQUEST
export const GET_SINGLE_SERIAL_NO_TRACK_DATA_REQUEST = 'GET_SINGLE_SERIAL_NO_TRACK_DATA_REQUEST'
export const GET_SINGLE_SERIAL_NO_TRACK_DATA_SUCCESS = 'GET_SINGLE_SERIAL_NO_TRACK_DATA_SUCCESS'
export const GET_SINGLE_SERIAL_NO_TRACK_DATA_FAIL = 'GET_SINGLE_SERIAL_NO_TRACK_DATA_FAIL'