// USER PASSWORD CHANGE
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCSESS = "USER_DETAILS_SUCSESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

// USER PASSWORD CHANGE
export const HISTORY_DATA_REQUEST = "HISTORY_DATA_REQUEST";
export const HISTORY_DATA_SUCCESS = "HISTORY_DATA_SUCCESS";
export const HISTORY_DATA_FAIL = "HISTORY_DATA_FAIL";